name: Check Bundle Size
on:
  pull_request:
    branches: [main]
jobs:
  checkBundleSizeChange:
    permissions:
      pull-requests: read
    name: Check whether PR increases bundle size more than 5%
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0 https://github.com/actions/checkout/commit/f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          ref: main
      - name: Setup Node.js 20
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1 https://github.com/actions/setup-node/commit/5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
        with:
          node-version: 20.x
      - name: Install dependencies
        run: yarn
      - name: Run build and analyze base bundle sizes
        env:
          CURRENT_BRANCH: ${{ github.base_ref }}
          CURRENT_REPO: ${{ github.repository }}
          NODE_OPTIONS: --max_old_space_size=4096
        run: ANALYZE=true yarn next-build
      - name: Check base bundle size of select pages
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1 https://github.com/actions/github-script/commit/d7906e4ad0b1822421a7e6a35d5ca353c962f410
        id: base-bundle-sizes
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { checkBundleSize } = require('./.github/workflows/scripts/check_bundle_size.js');
            return checkBundleSize();
      - name: Checkout PR branch
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0 https://github.com/actions/checkout/commit/f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node.js 20
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v.3.8.1 https://github.com/actions/setup-node/commit/5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
        with:
          node-version: 20.x
      - name: Install dependencies
        run: yarn
      - name: Run build and analyze head bundle sizes
        env:
          CURRENT_BRANCH: ${{ github.head_ref }}
          CURRENT_REPO: ${{ github.repository }}
          NODE_OPTIONS: --max_old_space_size=4096
        run: ANALYZE=true yarn next-build
      - name: Check head bundle size of select pages
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1 https://github.com/actions/github-script/commit/d7906e4ad0b1822421a7e6a35d5ca353c962f410
        id: head-bundle-sizes
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { checkBundleSize } = require('./.github/workflows/scripts/check_bundle_size.js');
            return checkBundleSize();
      - name: Compare bundle page bundle sizes
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1 https://github.com/actions/github-script/commit/d7906e4ad0b1822421a7e6a35d5ca353c962f410
        id: compare-bundles
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { compareBundles } = require('./.github/workflows/scripts/check_bundle_size.js');
            const baseBundles = ${{ steps.base-bundle-sizes.outputs.result }}
            const headBundles = ${{ steps.head-bundle-sizes.outputs.result }}
            return await compareBundles(baseBundles, headBundles)
      - name: Fail if bundle size growth exceeds 5% on any of the selected pages
        if: ${{ steps.compare-bundles.outputs.result > 0 }}
        run: exit 1
