name: Validate Redirects
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
env:
  BUILD_DIR: 'client/www/next-build'
permissions:
  contents: read
jobs:
  ValidateRedirects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Setup Node.js 20.x
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: yarn
      - name: Validate redirects
        id: redirects
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          result-encoding: string
          script: |
            const { invalidRedirects } = require('./.github/workflows/scripts/validate-redirects.js');
            return await invalidRedirects();
      - name: Fail if any invalid redirects have been found
        if: ${{ steps.redirects.outputs.result }}
        run: exit 1 && echo ${{ steps.redirects.outputs.result }}
